#!/bin/bash

function createwinenftmsp() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/winenftmsp.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/winenftmsp.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-winenftmsp --tls.certfiles "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-winenftmsp.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-winenftmsp.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-winenftmsp.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-winenftmsp.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy winenftmsp's CA cert to winenftmsp's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem" "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/msp/tlscacerts/ca.crt"

  # Copy winenftmsp's CA cert to winenftmsp's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem" "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/tlsca/tlsca.winenftmsp.example.com-cert.pem"

  # Copy winenftmsp's CA cert to winenftmsp's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem" "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/ca/ca.winenftmsp.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-winenftmsp --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-winenftmsp --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-winenftmsp --id.name winenftmspadmin --id.secret winenftmspadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-winenftmsp -M "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/peers/peer0.winenftmsp.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/peers/peer0.winenftmsp.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-winenftmsp -M "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/peers/peer0.winenftmsp.example.com/tls" --enrollment.profile tls --csr.hosts peer0.winenftmsp.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/peers/peer0.winenftmsp.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/peers/peer0.winenftmsp.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/peers/peer0.winenftmsp.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/peers/peer0.winenftmsp.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/peers/peer0.winenftmsp.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/peers/peer0.winenftmsp.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-winenftmsp -M "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/users/User1@winenftmsp.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/users/User1@winenftmsp.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://winenftmspadmin:winenftmspadminpw@localhost:7054 --caname ca-winenftmsp -M "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/users/Admin@winenftmsp.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/winenftmsp/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/winenftmsp.example.com/users/Admin@winenftmsp.example.com/msp/config.yaml"
}